### ISSUE TITLE
Share OBD connection in multiple view controllers

### ISSUE THREAD

**Issue by xixinjie** [lemberg/obd2-swift-lib#10]
Hi @OverSwift @hellensoloviy @MaxVitruk @sergiyloza  , I'd like to leverage your lib in my app. My concern is:
* Share OBD connection in multiple view controllers
* Run multiple OBD requests in one view controller
* Extend OBD commands, what if I have to support other OBD modes and pids, using swift extension?
* Encapsulate request and response into an object, just like [obj-java-api](https://github.com/pires/obd-java-api)

Do you have any suggestion?

**Comment by tropicdome** [comment]
Hi. I have more or less the same questions, and as follow-up would like to know

- Can the OBD connection be run as a shared instance, or do you have to make your own singleton to reuse it across the entire app?
- If you have to run multiple requests, does each request require their own observer e.g. if they are from Mode1?
- What is the maximum number of simultaneous requests you can run at a time? I read in the ELM327 documentation that you can chain 6 commands together in one request, but it does not say how much you can request in totalt, only that as long as you are reading the buffer, you should be ok.

Thanks

**Comment by MaxVitruk** [comment]
Hello @xixinjie & @tropicdome. 

Share OBD connection in multiple view controllers
Run multiple OBD requests in one view controller
Extend OBD commands, what if I have to support other OBD modes and pids, using swift extension?
Encapsulate request and response into an object, just like obj-java-api

@xixinjie 
Its all about your own implementation. Single responsibility - that what a lib does.
To implement shared connection you could create singleton class. Depends on your architecture solution.

Extend OBD commands - You could fork a lib to extend source code at all. Lib core works with a generics so you need just implements few interfaces to create your own command support.

Encapsulate request and response - Swift != Java :)


@tropicdome 
run multiple requests - You could turn repeatable for each command. If we are talking about different command - yes, you need request stack. Otherwise parser could not detect command response.

maximum number of simultaneous requests - Just one. We are storing each request in a queue.

Thanks.

**Comment by xixinjie** [comment]
Thank you @MaxVitruk . 
I'm now using singleton class to share connection. Will try other items then.
